### ISSUE TITLE
make Filter for minimum coverage adjustable over the settings file

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#105]
There should be a way to assign minium read covergae for every experiment. 
Default should be 50 or 100. 

Position to adjust would be: https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/524ed4832a6972fd695c0eeec25264188710a143/scripts/report_scripts/variantreport_p_sample.Rmd#L255

**Comment by jonasfreimuth** [comment]
See #117. Or did you mean for every individual sample?

**Comment by jonasfreimuth** [comment]
Closing this as #117 is also closed.
