### ISSUE TITLE
test files in root dir

### ISSUE THREAD

**Issue by jonasfreimuth** [BIMSBbioinfo/pigx_sarscov2_ww#111]
After `configure` the following files were present in my pipeline root dir: 

*  `test.sh`
*  `test.sh.log`
*  `test.sh.trs`

I have the feeling they ought to be in the tests dir, but am not sure.

**Comment by vicfabienne** [comment]
Yes, I realized that too and feel the same. 
I think that's @alexg9010 playground. Maybe you can help here?

**Comment by alexg9010** [comment]
These files are build upon configuration from the test.sh.in template and upon  make check /distcheck. This very rudimentary test file runs the whole pipeline and verifies if a certain file is generated.

We kept this file at the root directory for all the other pipelines aswell, but I don't know if this is strictly required. 

If your main concern is about wether to track changes in these files or not, I think we can safely add them to  .gitignore to not have them in our git history.

**Comment by rekado** [comment]
In the other pipelines we also git-ignore these files.

**Comment by jonasfreimuth** [comment]
PR #118 should close this
