### ISSUE TITLE
Broken link in `CONTRIBUTING`; line 47

### ISSUE THREAD

**Issue by jonasfreimuth** [BIMSBbioinfo/pigx_sarscov2_ww#112]

**Comment by jonasfreimuth** [comment]
Found another in `variantreport_p_sample.Rmd` (https://bioinformatics.mdc-berlin.de/pigx_docs/pigx-sars-cov-2.html#output-description)

**Comment by rekado** [comment]
These links are actually correct --- it's just that pigx_docs hasn't been rebuilt/published yet.  I'll rebuild pigx_docs in a moment.

**Comment by rekado** [comment]
See https://github.com/BIMSBbioinfo/pigx_docs/commit/fdd08d0bb4902a7a20c83bc07449a03d9838481f

This used to be auto-published by a travis-ci job, but that appears to be defunct.

**Comment by rekado** [comment]
I built the site and pushed the result to gh-pages on the pigx_docs repo.
