### ISSUE TITLE
clean up variant_report

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_sarscov2_ww#114]
shouldn't we filter all_variants instead of having a one-branch if here?

_Originally posted by @rekado in https://github.com/BIMSBbioinfo/pigx_sars-cov-2/pull/100#discussion_r844967748_

**Comment by alexg9010** [comment]
Please invert the if condition.  When using if / else always aim to use a positive condition.

_Originally posted by @rekado in https://github.com/BIMSBbioinfo/pigx_sars-cov-2/pull/100#discussion_r844966801_

**Comment by alexg9010** [comment]
weird indentation.

_Originally posted by @rekado in https://github.com/BIMSBbioinfo/pigx_sars-cov-2/pull/100#discussion_r844967342_

**Comment by alexg9010** [comment]
shouldn't this condition be merged with the above?  This would reduce unnecessary nesting.

_Originally posted by @rekado in https://github.com/BIMSBbioinfo/pigx_sars-cov-2/pull/100#discussion_r844968194_

**Comment by alexg9010** [comment]
Let's delete this instead of commenting it.  It's either needed or not.  Let's not clutter this already cluttered file :)

_Originally posted by @rekado in https://github.com/BIMSBbioinfo/pigx_sars-cov-2/pull/100#discussion_r844968818_

**Comment by alexg9010** [comment]
Don't use hardcoded folder names. Instead, pass the full path via the report parameters and the associated snakemake rule. 

https://github.com/BIMSBbioinfo/pigx_sars-cov-2/blob/4150b98d9f8be2866c5f9d56881dfdabcad1aa7c/scripts/report_scripts/variantreport_p_sample.Rmd#L50-L51

**Comment by jonasfreimuth** [comment]
Should all be fixed in #121

**Comment by jonasfreimuth** [comment]
Most of these are not even relevant any more, the rest is fixed. Probably all already in #131.
