### ISSUE TITLE
make running iVar/primer trimming optional 

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#116]
**Problem** 

Sometimes data needs so primer trimming and/or is better of without it. In this case it should be able to skip/bypass the [primertrimming step, currently performed by iVar](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/blob/21fe683902bcb45fcb2a71b61fb1b3f023ead0cd/snakefile.py#L321).

**Possible solution** 
One possible idea would be to enable to provide iVar with some kind of "dummy primerfile" or an empty one or smth and the ivar process should have no effect at all on the data then. However, we tried this at some point already and it always lead to ivar trimming either all the reads or in a very weird way. But it's likely that this behaviour can be changed by using different options in ivar. 

Another idea would be to implement some snakemake magic, so that in the absence of a provided primer-file all but the ivar rule is executed. 

**Relevant code**
[This branch](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/tree/tmp_improved_deconv_no_ivar) already carries a no-ivar version but only trough[ removing it](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/commit/9617755d4efdb0887343d1389bfca693d6f3f0a7) which only was supposed to be a temporary hackt tough.

**Comment by jonasfreimuth** [comment]
[Fix](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/commit/dbf29656e4636c12f133f0c3b7fb601e843cbf07) is merged now. Although I just noticed the `RUN_IVAR_PRIMER_TRIMING` var is spelled wrong, and it would have been nicer if that commit was more atomic...
