### ISSUE TITLE
make read coverage filter for mutations dynamically 

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#117]
**Problem** 
The variant-report now filters for [mutations that have minimal coverage](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/blob/main/scripts/report_scripts/variantreport_p_sample.Rmd#L256). However this is a paramter that can improve but also decrease the deconv. results and the optimal value is highly dependent on the datatype. 

**Issue**
This paramter should be given as input paramter through the [settings file](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/blob/tmp_improved_deconv_no_ivar/etc/settings.yaml.in) with a default of e.g. 50 or smth like that.

**Comment by jonasfreimuth** [comment]
This will be resolved in #121

**Comment by jonasfreimuth** [comment]
Branch in question: [general-improvements](https://github.com/jonasfreimuth/pigx_sars-cov-2/tree/general-improvements)

**Comment by jonasfreimuth** [comment]
[Fix](https://github.com/BIMSBbioinfo/pigx_sars-cov-2/commit/b1ba67434b246d2e6147ea5984f444b150203d49) is merged now.
