### ISSUE TITLE
Update example report in README

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#120]
The repos README links to a example report. This one is long outdated. 
A report with the latested version of the pipeline should be generated and linked there. 
That's also rather important/urgent because when ppl are visiting the Repo and see this as the expected output they might get disapointed because the reports look way better now.

**Comment by nanounanue** [comment]
Just checked this and the link now is broken (i.e. `404 error`)

**Comment by jonasfreimuth** [comment]
Thank you for reporting! PR #150 will fix the link and update the report to the version in the published paper.

**Comment by vicfabienne** [comment]
fixed
