### ISSUE TITLE
m4/ax_r_package.m4 is outdated

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_sarscov2_ww#123]
Use the latest version at https://savannah.gnu.org/patch/index.php?10191

**Comment by jonasfreimuth** [comment]
How does one update to this specific version? Do we need to wait for the path to be accepted and then update guix? Or is it possible to get these changes directly?

**Comment by rekado** [comment]
We just keep a copy of that file.  I'll try to get around to it this week.

**Comment by rekado** [comment]
Fixed in 61629e84d94793c73ebc31fa9aa64b76a3e8fb44
