### ISSUE TITLE
Allow .gz compressed reads as input

### ISSUE THREAD

**Issue by dohmjan** [BIMSBbioinfo/pigx_sarscov2_ww#24]
It should be possible that one can either provide *.fastq or compressed *.fastq.gz as input reads.

**Comment by alexg9010** [comment]
this should be quite easy, as PRINSEQ allows reading input from stdin, so you could use an input function that checks for possible compression and builds a decompression command, possibly using `gzcat`  or better `gzip -c` .

**Comment by vicfabienne** [comment]
fixed on development branch
