### ISSUE TITLE
`Show Code` on variant report page has no effect

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_sarscov2_ww#25]
This might also be the case for the other reports.

**Comment by al2na** [comment]
we don't need to show code, but I'm not sure.

**Comment by vicfabienne** [comment]
@rekado I think this thing comes from the template that is shared by all the reports. 
Can you maybe give a hint where someone would to have to start looking to fix - or remove that button?

**Comment by alexg9010** [comment]
Often this stems from adding include=FALSE to chunk options.

**Comment by jonasfreimuth** [comment]
Will be fixed in #121

**Comment by jonasfreimuth** [comment]
The branch in question is this [here](https://github.com/jonasfreimuth/pigx_sars-cov-2/tree/minor-fixes), but it will just remove the button alltogether. All relevant computation code is now in separate scripts, so I don't think showing the code would be particularly helpful anyway...
