### ISSUE TITLE
Allow single-end reads

### ISSUE THREAD

**Issue by dohmjan** [BIMSBbioinfo/pigx_sarscov2_ww#29]
It would make sense to not being limited to paired-end reads (R1 + R2) as it is so far. 
For this also see: https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/master/snakefile.py#L264

**Comment by al2na** [comment]
so far we have paired-end reads, when we have single-end we can change the priority here

**Comment by vicfabienne** [comment]
Single-end will be needed for ppl e.g. having MinIon data, which will IMO increase the applicability of the pipeline also in projects with different sequencing approaches or even less sequencing ressources.

**Comment by al2na** [comment]
@vfschumann is this done?

**Comment by vicfabienne** [comment]
fixed in PR #100
