### ISSUE TITLE
Lookup sample file names

### ISSUE THREAD

**Issue by dohmjan** [BIMSBbioinfo/pigx_sarscov2_ww#30]
Make input naming more flexible by obtaining file names from sample_sheet.
Especially relevant here: https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/main/snakefile.py#L134-L145

Consider something like this: https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/master/snakefile.py#L273

**Comment by al2na** [comment]
if you think this higher priority please adjust

**Comment by vicfabienne** [comment]
fixed on development branch
