### ISSUE TITLE
variantreport: all params variables should be passed in the header

### ISSUE THREAD

**Issue by mirifax** [BIMSBbioinfo/pigx_sarscov2_ww#31]
more of a comment: all variables should be defined in the header section for convenience. For example params$.. should not be somewhere down in the script in case we need to change it ..

**Comment by rekado** [comment]
`params` *is* a variable, though.  There is no point in defining `foo <- params$foo` to use `foo` instead of `params$foo` below.  We should do without this extra assignment clutter.
