### ISSUE TITLE
Trimming: specify read length cut off parameter

### ISSUE THREAD

**Issue by dohmjan** [BIMSBbioinfo/pigx_sarscov2_ww#34]
Get read length and specify cut off. Perhaps one should be able to vary this via the settings file.

See: https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/main/snakefile.py#L143

**Comment by mirifax** [comment]
I just discussed this with @vfschumann. The read length could vary per sample, so this should be provided in the sample file. The cut_off should at least have a default setting, but this could also be nice for experienced users to add per sample.
The first qc check before running the pipeline provides the read length (so this could either be manually added to the sample sheet by the user or mazbe even automatically ?). I did not see read length provided in the sample sheet in the other pigx pipeline- so maybe to be further discussed..

**Comment by rekado** [comment]
Cut off and default read length are now specified in the settings file.
