### ISSUE TITLE
navbar without doublets

### ISSUE THREAD

**Issue by mirifax** [BIMSBbioinfo/pigx_sarscov2_ww#36]
the "Timecourse" should not have a tab in the navbar. It is displayed already as the landing page aka "reports".
Also there is the Tab SARS_cov-2-variant .., which does not display anything ( should this maybe be instead of "reports" ?)

**Comment by rekado** [comment]
I don't see a tab "SARS_cov-2-variant".  Can you please provide more details?

**Comment by mirifax** [comment]
when i run the pipeline I see the following tabs: Reports, Overview, Timecourse(should be removed because same content as reports), Quality control, taxonomy, SARS-Cov-2 variant report (can not click on samles) and Variant report. 

I was also wondering where it comes from, but I only see it as as title in the header of the Rmds

Is it only me seeing it?

**Comment by rekado** [comment]
> Is it only me seeing it?

Probably.

The navbar is generated from Rmd files that exist in the report_scripts directory.  What files do you have there?

**Comment by rekado** [comment]
I merged the overview and the timecourse page.
