### ISSUE TITLE
Increase Transparency  in Plot Signature mutations by location

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_sarscov2_ww#41]

**Comment by rekado** [comment]
We plot a lot of traces on exactly the same spot, which is why it appears that transparency is insufficient.  In fact, we *have* already reduced the opacity by a lot, so I don't think it's feasible to reduce it even further.

Perhaps a different type of visualization is needed?  What do you think?

**Comment by al2na** [comment]
I think this will be fixed when we plot only interesting variants, the ones above a cutoff and have an increasing trend

**Comment by vicfabienne** [comment]
fixed on development branch
