### ISSUE TITLE
user_installation_doc.md  issues

### ISSUE THREAD

**Issue by rcuadrat** [BIMSBbioinfo/pigx_sarscov2_ww#45]
on user_installation_doc.md: 

- [x] 'cd pigx_sarscov2_ww.git' should be 'cd pigx_sarscov2_ww'
- [x] 'DBNAME=tests/databases/krona_db/' should be just 'DBNAME=krona_db/' (because in the previous step we did 'cd tests/databases'
- [x] the same for VEP dabase: 'DBNAME=tests/databases/vep_db/' should be 'DBNAME=vep_db/'

**Comment by rekado** [comment]
All done on `main`.
