### ISSUE TITLE
restructure snakemake file

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#62]
So far the snakemake file contains all the rules in one file. 

This makes it more complicated to work on it and to maintain it. 
I think a more proper way would be to make separate files for rules that belong together and call them from the snakefile by include.

**Comment by rekado** [comment]
Not sure we should do this.  I don't think it's any more complicated to work on the pipeline the way it is.  I suggested this very early on to avoid merge conflicts, but that train has left the station a long time ago.

**Comment by vicfabienne** [comment]
Closed because we discussed that it is irrelevant.
