### ISSUE TITLE
variant_report: Fix implementation of sigmut table deduplication

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#66]
## The problem 
When generating the signature matrixes (columns: variants, rows: mutations) it can happen that multiple columns are identical. This breaks the deconvolution. What has to be done here is to merge those duplicate columns but also preserving the column names. Example: when the two columns "b117" and column "b1459" are identical, they have to be merged to get a new column "b117, b1459".

However, there can be multiple identical pairs. Meaning we would need to have a column "b117, b1459" and another merged column "WT, b1349" and so on. 
In the way it is implemented right now the above example will merge all identicals into one big group. We only get one column "b117, b1459, WT, b1349". 
But this is wrong and the differentiation between those groups is important to get the correct deconvolution values. 

## Ideas on how to fix
I fixed this problem once with a function which is right now only present in a previous pull request #48 . But this function has very bad code style. rekardo commented on the flaws already. But this could be a starting point already. 

## Relevant lines 
[dedupe](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/variantreport_p_sample.Rmd#L190) is the current function which needs to be reworked.

the relevant chunk is [collapse_identicals](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/variantreport_p_sample.Rmd#L446)

**Comment by rekado** [comment]
There is no open PR.  Can you link the comments?

**Comment by vicfabienne** [comment]
https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/pull/48

**Comment by vicfabienne** [comment]
fixed on "WIP_seperating_deconvolution"

**Comment by vicfabienne** [comment]
fixed on development branch
