### ISSUE TITLE
Refine Test-sample-set

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#69]
We have test samples that sometimes failed at some point. I think they can give valuable insights when developing things further.

Can we maybe refine our test sample sheet which is used by make integration to include those problematic tests and throw out some of the others also to shorten that test-time a bit - maybe some of them don't fail anymore - if they still do we should investigate that.

**Comment by al2na** [comment]
we close this for now
