### ISSUE TITLE
variant_report: merge mutation frequencies when they contribute to the same aa freq

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#70]
![image (13)](https://user-images.githubusercontent.com/19505743/120874323-6da98000-c5a6-11eb-872c-8088d592e163.png)

## Description
When multiple genomic mutations lead to the same AA mutation, they are listed as separate mutations. This leads to breakage when generating the csvs for the plots but also to wrong deconvolution results. 

## What's need to be done? 
In this case the affected rows would have to be merged with adding up the frequency values in the 3ed column. This would have to be performed on [this "complete.df](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/variantreport_p_sample.Rmd#L298)".

**Comment by al2na** [comment]
where are the lines/files affected, that needed to be changed?

**Comment by vicfabienne** [comment]
[debug_completeDF.csv](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/files/6944876/debug_completeDF.csv)

This is the complete.df from the sample where this bug is from. Maybe hepls when debugging

**Comment by vicfabienne** [comment]
fixed on "WIP_fix_issue#70"

**Comment by vicfabienne** [comment]
we changed from working with aa mutations to only work with NT mutations. They will only be translated to aa mutations for reporting and summary purposes. 
With this, this issue is not a problem anymore
