### ISSUE TITLE
Ressource managements

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#71]
state where to find the resource management options in the documentation

from @rekado :
" see etc/settings.yaml.in, hat's the default settings that apply when nothing else in configured; the execution section specifies 6 jobs.  You can override that by adding execution:\n  jobs: n (for a given n) to your settings.yaml.

whatever setting is not in settings.yaml the default settings in etc/settings.yaml are consulted. "

**Comment by rekado** [comment]
The section "Running the pipeline" mentions the "execution" settings.
