### ISSUE TITLE
QC-report: find&fix bug that leads to negative coverage values

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#85]
![image](https://user-images.githubusercontent.com/19505743/123669452-60e21a00-d83c-11eb-9a8b-6ba5fcb6343f.png)

This happens in only one sample(so far): WW_210318_KW3 

I don't know how and why yet. The issue could either be in the [parsing script](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/main/scripts/get_qc_table.py) or in the [qc_report script](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/qc_report_per_sample.Rmd#L52).

There shouldn't be values below 0.

**Comment by al2na** [comment]
please put more details on which files/lines try problem comes from

**Comment by vicfabienne** [comment]
fixed on "WIP_primer_adpter_trimming"
