### ISSUE TITLE
QC reports: fix & order row/column names 

### ISSUE THREAD

**Issue by vicfabienne** [BIMSBbioinfo/pigx_sarscov2_ww#86]
![image](https://user-images.githubusercontent.com/19505743/123669863-d948db00-d83c-11eb-8d39-ce16423042e8.png)

The row names are switched. It should be:
1. Aligned reads 
2. Total coverage
3. Mean depth 

When fixing this issue also those issues should be fixed: 
- [ ] dots instead of white space
- [ ] more descriptive row names (which covergae, which depth...)
- [ ] the column name should not be V1. It think it could be just none
- [ ] The text says "pre-processed reads" - that's not true. It's coming from the aligned reads.

**Comment by al2na** [comment]
please provide the link to relevant lines

**Comment by vicfabienne** [comment]
fixed on development branch
