### ISSUE TITLE
Checking for pandoc-citeproc is obsolete

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_sarscov2_ww#98]
Newer versions of pandoc no longer distribute pandoc-citeproc as a separate tool.  We're still checking for it but don't use it directly.
We should remove the configure-time check for pandoc-citeproc.  This requires updating of the pigx-common submodule.  That submodule was the only user of pandoc-citeproc, and recent versions no longer need it.

**Comment by jonasfreimuth** [comment]
is this already resolved?

**Comment by rekado** [comment]
Yes.

https://github.com/BIMSBbioinfo/pigx_sars-cov-2/commit/69d3ce9a7c1f649762603cca0285076c5416ead7
